---
- hosts: all
  become: true
  vars:
    moto: Hello my friend!
  tasks:
  - name: Change /etc/motd
    copy:
      content: "{{moto}}"
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
